#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Convert an optional Windows path ("E:\workspace\dsh_project") to a Git Bash
# path ("/e/workspace/dsh_project"). No-op for already-POSIX paths.
to_posix() {
  local p="$1" drive rest
  if [[ "$p" =~ ^[A-Za-z]: ]]; then
    drive="${p:0:1}"; drive="${drive,,}"
    rest="${p:2}"
    printf '/%s%s' "$drive" "${rest//\\//}"
  else
    printf '%s' "$p"
  fi
}

# Repository root: first argument if given, else the current directory.
REPO_ROOT="$(to_posix "${1:-$PWD}")"
cd "$REPO_ROOT"

TOTAL_STAGES=6

banner "Create a personal GitHub repo"

# ── Stage 1: prerequisites ────────────────────────────────────────────────
stage "Prerequisites"
say "Repository root: $REPO_ROOT"
if ! command -v git >/dev/null 2>&1; then
  warn "git not found."
  open_url "https://git-scm.com/downloads"
  note "or: winget install Git.Git"
  pause "Installed? Press Enter (or Ctrl-C to abort)"
fi
if ! command -v gh >/dev/null 2>&1; then
  warn "GitHub CLI (gh) not found."
  open_url "https://cli.github.com"
  note "or: winget install GitHub.cli"
  pause "Installed? Press Enter (or Ctrl-C to abort)"
fi
say "git: $(git --version)"
say "gh:  $(gh --version 2>/dev/null | head -n1)"
pause "Continue?"

# ── Stage 2: authenticate with GitHub ─────────────────────────────────────
stage "GitHub authentication"
if gh auth status >/dev/null 2>&1; then
  say "Already authenticated:"
  gh auth status 2>&1 | sed 's/^/  /'
  pause "Continue with this account?"
else
  say "You're not logged into GitHub yet. A browser will open."
  step "Copy the one-time code gh prints below, paste it in the browser, and authorize."
  gh auth login --hostname github.com --git-protocol https --web
  pause "Logged in? Press Enter"
fi

# ── Stage 3: repository details ───────────────────────────────────────────
stage "Repository details"
ask REPO_NAME "Repository name:"
[[ -z "$REPO_NAME" ]] && REPO_NAME="$(basename "$REPO_ROOT")"
say "Visibility:"
printf '  %s•%s 1) public (anyone can read)\n' "$BLUE" "$RESET"
printf '  %s•%s 2) private (only you)\n' "$BLUE" "$RESET"
printf '  %s%s%s ' "$BOLD" "Choose [1/2] (Enter = public):" "$RESET"
read -r VIS_REPLY || true
REPO_VIS="public"
[[ "$VIS_REPLY" == "2" ]] && REPO_VIS="private"
ask REPO_DESC "Description (optional):"

# ── Stage 4: git identity ─────────────────────────────────────────────────
stage "Git identity"
if git config --global --get user.name >/dev/null 2>&1 && git config --global --get user.email >/dev/null 2>&1; then
  say "Commit identity: $(git config --global --get user.name) <$(git config --global --get user.email)>"
  pause "Use it? (Ctrl-C to change)"
else
  say "No commit name/email configured globally yet."
  ask GIT_NAME "Your name:"
  ask GIT_EMAIL "Your email:"
  git config --global user.name "$GIT_NAME"
  git config --global user.email "$GIT_EMAIL"
  note "set globally (applies to all your repos)."
fi

# ── Stage 5: initialize & first commit ────────────────────────────────────
stage "Initialize & first commit"
if git rev-parse --git-dir >/dev/null 2>&1; then
  say "Already a git repository; skipping init."
else
  git init
fi
if git rev-parse --verify HEAD >/dev/null 2>&1; then
  say "Commits already exist; skipping first commit."
else
  git add -A
  if git commit -m "Initial commit" --quiet; then
    note "created the initial commit."
  else
    warn "nothing to commit, or the commit failed (see above)."
    pause "Continue anyway?"
  fi
fi

# ── Stage 6: create & push to GitHub ──────────────────────────────────────
stage "Create & push to GitHub"
say "Repository: $REPO_NAME  ·  visibility: $REPO_VIS"
[[ -n "$REPO_DESC" ]] && say "Description: $REPO_DESC"
git remote remove origin 2>/dev/null || true
if gh repo view "$REPO_NAME" >/dev/null 2>&1; then
  warn "'$REPO_NAME' already exists under your account."
  confirm "Point origin at it and push?" || { note "Nothing pushed."; exit 0; }
  OWNER="$(gh api user --jq .login)"
  git remote add origin "https://github.com/$OWNER/$REPO_NAME.git"
else
  confirm "Create '$REPO_NAME' ($REPO_VIS) and push your files?" || { note "Nothing pushed."; exit 0; }
  ARGS=(repo create "$REPO_NAME" "--$REPO_VIS" --source=. --remote=origin)
  [[ -n "$REPO_DESC" ]] && ARGS+=(--description "$REPO_DESC")
  gh "${ARGS[@]}"
fi
git branch -M main 2>/dev/null || true
git push -u origin main

finish
